name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test data files exist
      run: |
        python -c "import pandas as pd; pd.read_csv('enhanced_leads_advanced.csv')"
        python -c "import pandas as pd; pd.read_csv('enhanced_calls_advanced.csv')"
        python -c "import pandas as pd; pd.read_csv('enhanced_schedule_advanced.csv')"
        python -c "import pandas as pd; pd.read_csv('agent_performance_advanced.csv')"
    
    - name: Test Streamlit app
      run: |
        python -c "import streamlit as st; import app_enhanced"
    
    - name: Run basic functionality tests
      run: |
        python -c "
        import pandas as pd
        import numpy as np
        from datetime import datetime
        
        # Test data loading
        leads_df = pd.read_csv('enhanced_leads_advanced.csv')
        calls_df = pd.read_csv('enhanced_calls_advanced.csv')
        
        print(f'✅ Loaded {len(leads_df)} leads successfully')
        print(f'✅ Loaded {len(calls_df)} calls successfully')
        
        # Test basic calculations
        total_pipeline = leads_df['RevenuePotential'].sum() if 'RevenuePotential' in leads_df.columns else 0
        success_rate = calls_df['IsSuccessful'].mean() if 'IsSuccessful' in calls_df.columns else 0
        
        print(f'✅ Pipeline calculation: ${total_pipeline:,.0f}')
        print(f'✅ Success rate calculation: {success_rate:.1%}')
        print('🎉 All basic tests passed!')
        "

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Security Scan
      run: |
        pip install bandit[toml]
        bandit -r . -f json -o bandit-report.json || true
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-security-report
        path: bandit-report.json

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t crm-dashboard:latest .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8501:8501 --name test-container crm-dashboard:latest
        sleep 30
        # Test if the app is responding
        curl -f http://localhost:8501/_stcore/health || exit 1
        docker stop test-container
        docker rm test-container

  deploy-preview:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate deployment preview
      run: |
        echo "🚀 Preview deployment would be created for PR #${{ github.event.number }}"
        echo "📊 Dashboard preview: https://pr-${{ github.event.number }}-executive-crm.streamlit.app"
        echo "✨ Features included in this PR:"
        echo "- Enhanced AI/ML analytics"
        echo "- Real-time dashboard updates"
        echo "- Advanced performance metrics"

  notify-deployment:
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment notification
      run: |
        echo "🎉 Main branch updated!"
        echo "🚀 Streamlit Cloud will auto-deploy the latest changes"
        echo "📊 Dashboard URL: https://executive-crm-dashboard.streamlit.app"
        echo "⏱️ Deployment typically takes 2-3 minutes"
