[theme]
primaryColor = "#f59e0b"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#1a202c"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[logger]
level = "info"

[client]
caching = true
displayEnabled = true
showErrorDetails = true
